export const carsData = [
  {
    id: 1,
    reviewer: 440,
    title: "Koenigsegg",
    type: "Sport",
    fuelCapacity: 90,
    steering: "Manual",
    capacity: 2,
    price: 99.0,
    discountRate: null,
    rating: 5,
    isFavorite: false,
    description: "A high-performance sports car for enthusiasts.",
    mainImg: "/src/assets/DetailedProduct/koenigsegg-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 2,
    reviewer: 440,
    title: "Nissan GT-R",
    type: "Sport",
    fuelCapacity: 80,
    steering: "Manual",
    capacity: 2,
    price: 80.0,
    discountRate: 25,
    rating: 4,
    isFavorite: true,
    description: "A legendary car known for its performance and design.",
    mainImg: "/src/assets/DetailedProduct/nissan-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 3,
    reviewer: 440,
    title: "Rolls-Royce",
    type: "Sedan",
    fuelCapacity: 70,
    steering: "Manual",
    capacity: 4,
    price: 96.0,
    discountRate: null,
    rating: 5,
    isFavorite: true,
    description: "Luxury at its finest with unmatched comfort.",
    mainImg: "/src/assets/DetailedProduct/rolls-royce-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 4,
    reviewer: 440,
    title: "All New Rush",
    type: "SUV",
    fuelCapacity: 70,
    steering: "Manual",
    capacity: 6,
    price: 72.0,
    discountRate: null,
    rating: 3,
    isFavorite: false,
    description: "An SUV designed for both urban and off-road adventures.",
    mainImg: "/src/assets/DetailedProduct/all-new-rush-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 5,
    reviewer: 440,
    title: "CR-V",
    type: "SUV",
    fuelCapacity: 80,
    steering: "Manual",
    capacity: 2,
    price: 80.0,
    discountRate: 20,
    rating: 4,
    isFavorite: true,
    description: "A reliable and versatile SUV for any journey.",
    mainImg: "/src/assets/DetailedProduct/cr-v-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 6,
    reviewer: 440,
    title: "All New Terios",
    type: "SUV",
    fuelCapacity: 70,
    steering: "Manual",
    capacity: 6,
    price: 72.0,
    discountRate: null,
    rating: 3,
    isFavorite: false,
    description: "A spacious SUV with modern features for families.",
    mainImg: "/src/assets/DetailedProduct/all-new-terios-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 7,
    reviewer: 440,
    title: "Nissan GT-R",
    type: "Sport",
    fuelCapacity: 80,
    steering: "Manual",
    capacity: 2,
    price: 80.0,
    discountRate: 15,
    rating: 4,
    isFavorite: true,
    description: "A powerful sports car that defines speed and precision.",
    mainImg: "/src/assets/DetailedProduct/nissan-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 8,
    reviewer: 440,
    title: "BMW X5",
    type: "SUV",
    fuelCapacity: 85,
    steering: "Automatic",
    capacity: 5,
    price: 90.0,
    discountRate: 10,
    rating: 5,
    isFavorite: true,
    description: "An iconic SUV blending luxury and performance.",
    mainImg: "/src/assets/DetailedProduct/bmw-x5-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 9,
    reviewer: 440,
    title: "Toyota Fortuner",
    type: "SUV",
    fuelCapacity: 75,
    steering: "Automatic",
    capacity: 6,
    price: 85.0,
    discountRate: null,
    rating: 4,
    isFavorite: false,
    description: "A rugged SUV built for adventure and durability.",
    mainImg: "/src/assets/DetailedProduct/toyota-fortuner-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
  {
    id: 10,
    reviewer: 440,
    title: "Audi A8",
    type: "Sedan",
    fuelCapacity: 80,
    steering: "Automatic",
    capacity: 4,
    price: 100.0,
    discountRate: 10,
    rating: 5,
    isFavorite: true,
    description: "A luxury sedan with advanced technology and style.",
    mainImg: "/src/assets/DetailedProduct/audi-a8-main.png",
    interior1: "/src/assets/DetailedProduct/nissan-interior-1.jpg",
    interior2: "/src/assets/DetailedProduct/nissan-interior-2.jpg",
  },
];
